"""Visual report builder — data models, SVG generation, and ASCII fallbacks.

Pure SVG charts that work in Markdown (via <img> data URIs), HTML reports,
and PDF export (WeasyPrint renders inline SVG natively).

No external charting dependencies — all SVG is generated by hand.
"""
from __future__ import annotations

import math
from dataclasses import dataclass, field
from typing import Any

# ── Color palette ────────────────────────────────────────────────────────────

COLORS = {
    "strengths": "#10b981",
    "weaknesses": "#ef4444",
    "opportunities": "#3b82f6",
    "threats": "#f59e0b",
    "grade_a": "#10b981",
    "grade_b": "#06b6d4",
    "grade_c": "#eab308",
    "grade_d": "#f97316",
    "grade_f": "#ef4444",
    "bg_dark": "#0f172a",
    "bg_panel": "#1e293b",
    "text_primary": "#f1f5f9",
    "text_muted": "#94a3b8",
    "border": "#334155",
    "accent": "#8b5cf6",
}

RADAR_COLORS = ["#8b5cf6", "#06b6d4", "#f59e0b", "#10b981", "#ef4444"]


# ── SWOT Quadrant ────────────────────────────────────────────────────────────


@dataclass
class SWOTQuadrant:
    strengths: list[str] = field(default_factory=list)
    weaknesses: list[str] = field(default_factory=list)
    opportunities: list[str] = field(default_factory=list)
    threats: list[str] = field(default_factory=list)


def build_swot_quadrant(swot: dict[str, Any]) -> SWOTQuadrant:
    sw = swot.get("swot", swot)
    return SWOTQuadrant(
        strengths=sw.get("strengths", ["—"]) or ["—"],
        weaknesses=sw.get("weaknesses", ["—"]) or ["—"],
        opportunities=sw.get("opportunities", ["—"]) or ["—"],
        threats=sw.get("threats", ["—"]) or ["—"],
    )


def swot_quadrant_svg(model: SWOTQuadrant, width: int = 800, height: int = 500) -> str:
    """Generate an SVG 2x2 quadrant chart."""
    half_w = width // 2
    half_h = height // 2
    pad = 20
    label_w = 80

    def _quadrant(x: int, y: int, w: int, h: int, label: str, color: str,
                  items: list[str]) -> str:
        lines = []
        lines.append(f'<rect x="{x}" y="{y}" width="{w}" height="{h}" '
                     f'fill="{COLORS["bg_panel"]}" stroke="{color}" stroke-width="1" rx="4"/>')
        # Label bar
        lines.append(f'<rect x="{x}" y="{y}" width="{w}" height="24" '
                     f'fill="{color}" rx="4"/>')
        lines.append(f'<text x="{x + 8}" y="{y + 17}" fill="white" '
                     f'font-family="sans-serif" font-size="12" font-weight="bold">{label}</text>')
        # Items
        text_y = y + 42
        for item in items[:6]:  # max 6 items per quadrant
            # Wrap long text
            wrapped = _wrap_text(item, w - pad * 2 - 8)
            for line in wrapped:
                lines.append(f'<text x="{x + pad}" y="{text_y}" '
                             f'fill="{COLORS["text_muted"]}" font-family="sans-serif" '
                             f'font-size="10">• {line}</text>')
                text_y += 14
        return "\n".join(lines)

    def _wrap_text(text: str, max_width: int, char_width: int = 5) -> list[str]:
        if len(text) * char_width <= max_width:
            return [text]
        words = text.split()
        lines: list[str] = []
        current = ""
        for w in words:
            if (current + " " + w).strip().__len__() * char_width <= max_width:
                current = (current + " " + w).strip()
            else:
                if current:
                    lines.append(current)
                current = w
        if current:
            lines.append(current)
        return lines

    quads = [
        (0, 0, half_w, half_h, "Strengths", COLORS["strengths"], model.strengths),
        (half_w, 0, half_w, half_h, "Weaknesses", COLORS["weaknesses"], model.weaknesses),
        (0, half_h, half_w, half_h, "Opportunities", COLORS["opportunities"], model.opportunities),
        (half_w, half_h, half_w, half_h, "Threats", COLORS["threats"], model.threats),
    ]

    parts = []
    for x, y, w, h, label, color, items in quads:
        parts.append(_quadrant(x, y, w, h, label, color, items))

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">
<rect width="{width}" height="{height}" fill="{COLORS["bg_dark"]}" rx="8"/>
{"".join(parts)}
</svg>"""


def swot_quadrant_ascii(model: SWOTQuadrant) -> str:
    """ASCII table fallback for Markdown reports."""
    lines = [
        "┌──────────────────┬──────────────────┐",
        "│    STRENGTHS     │    WEAKNESSES    │",
        "├──────────────────┼──────────────────┤",
    ]
    max_items = max(len(model.strengths), len(model.weaknesses), 1)
    for i in range(max_items):
        s = model.strengths[i] if i < len(model.strengths) else ""
        w = model.weaknesses[i] if i < len(model.weaknesses) else ""
        lines.append(f"│ {_pad(s, 16)} │ {_pad(w, 16)} │")
    lines += [
        "├──────────────────┼──────────────────┤",
        "│  OPPORTUNITIES   │     THREATS      │",
        "├──────────────────┼──────────────────┤",
    ]
    max_items = max(len(model.opportunities), len(model.threats), 1)
    for i in range(max_items):
        o = model.opportunities[i] if i < len(model.opportunities) else ""
        t = model.threats[i] if i < len(model.threats) else ""
        lines.append(f"│ {_pad(o, 16)} │ {_pad(t, 16)} │")
    lines.append("└──────────────────┴──────────────────┘")
    return "\n".join(lines)


def _pad(text: str, width: int) -> str:
    return (text[:width - 1] if len(text) >= width else text).ljust(width)


# ── Radar Chart ──────────────────────────────────────────────────────────────


@dataclass
class RadarSeries:
    name: str
    values: list[float]  # 0-100 per axis


@dataclass
class RadarChart:
    axes: list[str]
    series: list[RadarSeries]


def build_radar_chart(competitor: dict[str, Any]) -> RadarChart:
    competitors = competitor.get("competitors", [])
    if not isinstance(competitors, list) or not competitors:
        return RadarChart(axes=[], series=[])

    # Extract normalized comparison axes
    axes = ["Pricing Tier", "Positioning", "Content Quality", "Services", "SEO"]
    field_map = {
        "Pricing Tier": "pricing_tier",
        "Positioning": "positioning",
        "Content Quality": "content_quality",
        "Services": "services",
        "SEO": "seo_notes",
    }
    text_values = {"Premium": 90, "Mid-range": 60, "Budget": 30,
                   "Enterprise": 90, "SMB": 50, "Consumer": 20,
                   "High": 90, "Medium": 60, "Low": 30}

    series: list[RadarSeries] = []
    for i, comp in enumerate(competitors[:5]):  # max 5 series
        if not isinstance(comp, dict):
            continue
        values = []
        for axis in axes:
            fname = field_map.get(axis, "")
            raw = comp.get(fname, "")
            if isinstance(raw, str):
                val = text_values.get(raw, 50)
            elif isinstance(raw, list):
                val = min(len(raw) * 20, 100)
            else:
                val = 50
            values.append(float(val))
        series.append(RadarSeries(name=comp.get("name", f"Competitor {i+1}"), values=values))

    return RadarChart(axes=axes, series=series)


def radar_chart_svg(model: RadarChart, width: int = 500, height: int = 400) -> str:
    """Generate an SVG radar/spider chart."""
    if not model.axes or not model.series:
        return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">
<rect width="{width}" height="{height}" fill="{COLORS["bg_dark"]}" rx="8"/>
<text x="{width//2}" y="{height//2}" fill="{COLORS["text_muted"]}" text-anchor="middle" font-family="sans-serif" font-size="14">No competitor data available</text>
</svg>"""

    cx, cy = width // 2, height // 2 + 10
    max_r = min(width, height) // 2 - 60
    n = len(model.axes)
    angle_step = 2 * math.pi / n

    def _polar(angle: float, r: float) -> tuple[float, float]:
        return (cx + r * math.cos(angle - math.pi / 2),
                cy + r * math.sin(angle - math.pi / 2))

    parts: list[str] = []
    # Grid rings
    for ring_pct in [0.25, 0.5, 0.75, 1.0]:
        r = max_r * ring_pct
        pts = [_polar(i * angle_step, r) for i in range(n)]
        pts_str = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
        parts.append(f'<polygon points="{pts_str}" fill="none" '
                     f'stroke="{COLORS["border"]}" stroke-width="0.5"/>')

    # Axis lines and labels
    for i, axis in enumerate(model.axes):
        angle = i * angle_step
        ex, ey = _polar(angle, max_r)
        parts.append(f'<line x1="{cx}" y1="{cy}" x2="{ex:.1f}" y2="{ey:.1f}" '
                     f'stroke="{COLORS["border"]}" stroke-width="0.5"/>')
        lx, ly = _polar(angle, max_r + 20)
        parts.append(f'<text x="{lx:.1f}" y="{ly:.1f}" text-anchor="middle" '
                     f'fill="{COLORS["text_muted"]}" font-family="sans-serif" '
                     f'font-size="10">{axis}</text>')

    # Data series
    for si, series in enumerate(model.series):
        color = RADAR_COLORS[si % len(RADAR_COLORS)]
        pts = []
        for i, v in enumerate(series.values[:n]):
            r = max_r * (min(max(v, 0), 100) / 100)
            pts.append(_polar(i * angle_step, r))
        pts_str = " ".join(f"{x:.1f},{y:.1f}" for x, y in pts)
        parts.append(f'<polygon points="{pts_str}" fill="{color}" fill-opacity="0.15" '
                     f'stroke="{color}" stroke-width="2"/>')

    # Legend
    legend_y = 15
    for si, series in enumerate(model.series):
        color = RADAR_COLORS[si % len(RADAR_COLORS)]
        lx = 10 + si * 100
        parts.append(f'<rect x="{lx}" y="{legend_y}" width="10" height="10" '
                     f'fill="{color}" rx="2"/>')
        parts.append(f'<text x="{lx + 14}" y="{legend_y + 9}" '
                     f'fill="{COLORS["text_muted"]}" font-family="sans-serif" '
                     f'font-size="10">{series.name}</text>')

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">
<rect width="{width}" height="{height}" fill="{COLORS["bg_dark"]}" rx="8"/>
{"".join(parts)}
</svg>"""


def radar_chart_ascii(model: RadarChart) -> str:
    """ASCII table fallback for Markdown reports."""
    if not model.axes or not model.series:
        return "*No competitor radar data available.*"
    header = "| Competitor | " + " | ".join(model.axes) + " |"
    sep = "|---|" + "|---" * len(model.axes) + "|"
    lines = [header, sep]
    for s in model.series:
        vals = " | ".join(f"{v:.0f}" for v in s.values)
        lines.append(f"| {s.name} | {vals} |")
    return "\n".join(lines)


# ── Bar Chart ────────────────────────────────────────────────────────────────


@dataclass
class BarChartItem:
    label: str
    value: float  # 0-100


@dataclass
class BarChart:
    title: str
    items: list[BarChartItem]


def build_content_gap_chart(seo: dict[str, Any]) -> BarChart:
    gaps = seo.get("content_gaps", [])
    weaknesses = seo.get("seo_weaknesses", [])
    items: list[BarChartItem] = []
    for i, gap in enumerate(gaps[:8]):
        score = 100 - (i * 10 + 20)  # descending priority
        items.append(BarChartItem(label=gap, value=max(score, 10)))
    for i, w in enumerate(weaknesses[:5]):
        score = 100 - (i * 15 + 10)
        items.append(BarChartItem(label=w, value=max(score, 10)))
    return BarChart(title="Content Gaps & SEO Weaknesses", items=items)


def bar_chart_svg(model: BarChart, width: int = 700, height: int | None = None) -> str:
    """Generate a horizontal bar chart SVG."""
    if not model.items:
        h = height or 200
        return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {h}" width="{width}" height="{h}">
<rect width="{width}" height="{h}" fill="{COLORS["bg_dark"]}" rx="8"/>
<text x="{width//2}" y="{h//2}" fill="{COLORS["text_muted"]}" text-anchor="middle" font-family="sans-serif" font-size="14">No data available</text>
</svg>"""

    bar_h = 24
    gap = 8
    label_w = 200
    max_bar_w = width - label_w - 80
    chart_h = len(model.items) * (bar_h + gap) + 40
    h = height or chart_h

    parts: list[str] = []
    # Title
    parts.append(f'<text x="10" y="20" fill="{COLORS["text_primary"]}" '
                 f'font-family="sans-serif" font-size="14" font-weight="bold">{model.title}</text>')

    y_offset = 35
    max_val = max((item.value for item in model.items), default=100)
    colors = ["#8b5cf6", "#06b6d4", "#10b981", "#f59e0b", "#ef4444", "#ec4899", "#14b8a6", "#6366f1"]

    for i, item in enumerate(model.items):
        color = colors[i % len(colors)]
        bar_w = max_bar_w * (item.value / max(max_val, 1))
        y = y_offset + i * (bar_h + gap)
        # Label
        label = item.label[:35] + ("..." if len(item.label) > 35 else "")
        parts.append(f'<text x="10" y="{y + bar_h - 6}" '
                     f'fill="{COLORS["text_muted"]}" font-family="sans-serif" font-size="10">{label}</text>')
        # Bar background
        parts.append(f'<rect x="{label_w}" y="{y}" width="{max_bar_w}" height="{bar_h}" '
                     f'fill="{COLORS["bg_panel"]}" rx="3"/>')
        # Bar fill
        parts.append(f'<rect x="{label_w}" y="{y}" width="{bar_w:.1f}" height="{bar_h}" '
                     f'fill="{color}" rx="3"/>')
        # Value
        parts.append(f'<text x="{label_w + bar_w + 5:.1f}" y="{y + bar_h - 6}" '
                     f'fill="{COLORS["text_primary"]}" font-family="sans-serif" '
                     f'font-size="10">{item.value:.0f}</text>')

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {h}" width="{width}" height="{h}">
<rect width="{width}" height="{h}" fill="{COLORS["bg_dark"]}" rx="8"/>
{"".join(parts)}
</svg>"""


def bar_chart_ascii(model: BarChart) -> str:
    """ASCII bar chart fallback for Markdown reports."""
    if not model.items:
        return f"*No data for: {model.title}*"
    lines = [f"**{model.title}**", ""]
    max_label = max(len(item.label) for item in model.items)
    for item in model.items:
        bar_len = int(item.value / 5)
        bar = "█" * bar_len + "░" * (20 - bar_len)
        lines.append(f"  {item.label.ljust(max_label)} │{bar}│ {item.value:.0f}")
    return "\n".join(lines)


# ── Score Donut ──────────────────────────────────────────────────────────────


@dataclass
class ScoreDimension:
    label: str
    value: float


@dataclass
class ScoreDonut:
    overall: float
    grade: str
    dimensions: list[ScoreDimension] = field(default_factory=list)


def build_score_donut(score: dict[str, Any]) -> ScoreDonut:
    overall = score.get("overall", 0)
    grade = score.get("grade", "")
    dim_fields = [
        ("Marketing Gap", "marketing_gap_severity"),
        ("AI Fit", "ai_automation_fit"),
        ("Local Relevance", "local_relevance"),
        ("Budget", "likely_budget"),
        ("Outreach", "outreach_ease"),
        ("Urgency", "urgency_signals"),
        ("Confidence", "data_confidence"),
    ]
    dimensions = []
    for label, field_name in dim_fields:
        v = score.get(field_name)
        if v is not None:
            dimensions.append(ScoreDimension(label=label, value=float(v)))
    return ScoreDonut(overall=float(overall), grade=str(grade), dimensions=dimensions)


def _grade_color(grade: str) -> str:
    if not grade:
        return COLORS["text_muted"]
    g = grade.upper()
    if g.startswith("A"):
        return COLORS["grade_a"]
    if g.startswith("B"):
        return COLORS["grade_b"]
    if g.startswith("C"):
        return COLORS["grade_c"]
    if g == "D":
        return COLORS["grade_d"]
    return COLORS["grade_f"]


def score_donut_svg(model: ScoreDonut, width: int = 300, height: int = 300) -> str:
    """Generate a donut chart SVG for prospect score."""
    cx, cy, r = width // 2, height // 2, 80
    stroke_w = 20
    circumference = 2 * math.pi * r
    pct = min(max(model.overall, 0), 100) / 100
    dash_len = circumference * pct
    gap = circumference - dash_len
    color = _grade_color(model.grade)

    parts: list[str] = []
    # Background circle
    parts.append(f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="none" '
                 f'stroke="{COLORS["border"]}" stroke-width="{stroke_w}"/>')
    # Foreground arc
    if dash_len > 0:
        parts.append(f'<circle cx="{cx}" cy="{cy}" r="{r}" fill="none" '
                     f'stroke="{color}" stroke-width="{stroke_w}" '
                     f'stroke-dasharray="{dash_len:.1f} {gap:.1f}" '
                     f'stroke-linecap="round" transform="rotate(-90 {cx} {cy})"/>')
    # Center text
    parts.append(f'<text x="{cx}" y="{cy - 8}" text-anchor="middle" '
                 f'fill="{color}" font-family="sans-serif" font-size="36" '
                 f'font-weight="bold">{model.overall:.0f}</text>')
    parts.append(f'<text x="{cx}" y="{cy + 16}" text-anchor="middle" '
                 f'fill="{COLORS["text_muted"]}" font-family="sans-serif" font-size="16">{model.grade}</text>')

    # Dimension dots
    dot_colors = ["#8b5cf6", "#06b6d4", "#10b981", "#f59e0b", "#ef4444", "#ec4899", "#14b8a6"]
    y_base = cy + 50
    for i, dim in enumerate(model.dimensions[:4]):
        dc = dot_colors[i % len(dot_colors)]
        dy = y_base + i * 18
        parts.append(f'<circle cx="{cx - 80}" cy="{dy}" r="4" fill="{dc}"/>')
        parts.append(f'<text x="{cx - 72}" y="{dy + 4}" '
                     f'fill="{COLORS["text_muted"]}" font-family="sans-serif" font-size="10">{dim.label}</text>')
        parts.append(f'<text x="{cx + 80}" y="{dy + 4}" text-anchor="end" '
                     f'fill="{COLORS["text_primary"]}" font-family="sans-serif" font-size="10">{dim.value:.0f}</text>')

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {height}" width="{width}" height="{height}">
<rect width="{width}" height="{height}" fill="{COLORS["bg_dark"]}" rx="8"/>
{"".join(parts)}
</svg>"""


def score_donut_ascii(model: ScoreDonut) -> str:
    """ASCII score display fallback for Markdown reports."""
    color_map = {"A+": "█", "A": "█", "B+": "▓", "B": "▓", "C+": "▒",
                 "C": "▒", "D": "░", "F": "░"}
    bar_char = color_map.get(model.grade, "▓")
    bar_len = int(model.overall / 5)
    bar = bar_char * bar_len + "░" * (20 - bar_len)
    return f"**Score: {model.overall:.0f}/100 — Grade: {model.grade}**\n\n`[{bar}]`\n"


# ── Automation Roadmap ───────────────────────────────────────────────────────


@dataclass
class RoadmapItem:
    phase: str
    title: str
    priority: str = "medium"  # high, medium, low
    description: str = ""


def build_automation_roadmap(swot: dict[str, Any]) -> list[RoadmapItem]:
    """Derive a prioritized automation roadmap from SWOT analysis."""
    sw = swot.get("swot", swot)
    items: list[RoadmapItem] = []

    weaknesses = sw.get("weaknesses", [])
    opportunities = sw.get("opportunities", [])

    # Map weaknesses to actionable items
    weakness_map = {
        "email": ("Phase 1", "Setup Email Marketing", "high"),
        "website": ("Phase 1", "Website Redesign", "high"),
        "seo": ("Phase 2", "SEO Optimization", "high"),
        "social": ("Phase 2", "Social Media Strategy", "medium"),
        "content": ("Phase 3", "Content Creation Pipeline", "medium"),
        "crm": ("Phase 3", "CRM Implementation", "medium"),
        "automat": ("Phase 4", "Workflow Automation", "high"),
        "online": ("Phase 2", "Online Ordering System", "high"),
    }

    combined = (weaknesses or []) + (opportunities or [])
    if not combined:
        combined = ["Improve website", "Setup email marketing", "Social media presence"]

    used_phases: set[str] = set()
    for item in combined[:8]:
        text = item.lower() if isinstance(item, str) else ""
        matched = False
        for keyword, (phase, title, priority) in weakness_map.items():
            if keyword in text and phase not in used_phases:
                items.append(RoadmapItem(phase=phase, title=title, priority=priority))
                used_phases.add(phase)
                matched = True
                break
        if not matched:
            phase = f"Phase {len(items) + 1}"
            items.append(RoadmapItem(
                phase=phase,
                title=item if isinstance(item, str) else "General Improvement",
                priority="medium",
            ))

    # Ensure we have at least one item
    if not items:
        items = [RoadmapItem(phase="Phase 1", title="Audit & Strategy", priority="high")]

    return items


def roadmap_svg(items: list[RoadmapItem], width: int = 700, height: int | None = None) -> str:
    """Generate an SVG roadmap/timeline."""
    priority_colors = {"high": "#ef4444", "medium": "#f59e0b", "low": "#10b981"}
    row_h = 50
    h = height or (len(items) * row_h + 80)

    parts: list[str] = []
    parts.append(f'<text x="10" y="25" fill="{COLORS["text_primary"]}" '
                 f'font-family="sans-serif" font-size="14" font-weight="bold">Recommended Automation Roadmap</text>')

    y_offset = 45
    timeline_x = 120
    for i, item in enumerate(items):
        y = y_offset + i * row_h
        color = priority_colors.get(item.priority, "#94a3b8")

        # Phase label
        parts.append(f'<text x="10" y="{y + 20}" fill="{COLORS["text_muted"]}" '
                     f'font-family="sans-serif" font-size="10" font-weight="bold">{item.phase}</text>')

        # Timeline dot
        parts.append(f'<circle cx="{timeline_x}" cy="{y + 17}" r="6" '
                     f'fill="{color}" stroke="{COLORS["bg_dark"]}" stroke-width="2"/>')

        # Line connector
        if i < len(items) - 1:
            parts.append(f'<line x1="{timeline_x}" y1="{y + 23}" '
                         f'x2="{timeline_x}" y2="{y + row_h + 11}" '
                         f'stroke="{COLORS["border"]}" stroke-width="1"/>')

        # Title
        parts.append(f'<text x="{timeline_x + 16}" y="{y + 17}" '
                     f'fill="{COLORS["text_primary"]}" font-family="sans-serif" '
                     f'font-size="12" font-weight="bold">{item.title}</text>')

        # Priority badge
        badge_x = width - 70
        parts.append(f'<rect x="{badge_x}" y="{y + 6}" width="50" height="20" '
                     f'fill="{color}" fill-opacity="0.2" rx="4"/>')
        parts.append(f'<text x="{badge_x + 25}" y="{y + 20}" text-anchor="middle" '
                     f'fill="{color}" font-family="sans-serif" font-size="9">{item.priority.upper()}</text>')

    return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} {h}" width="{width}" height="{h}">
<rect width="{width}" height="{h}" fill="{COLORS["bg_dark"]}" rx="8"/>
{"".join(parts)}
</svg>"""


def roadmap_ascii(items: list[RoadmapItem]) -> str:
    """ASCII timeline fallback for Markdown reports."""
    lines = ["**Recommended Automation Roadmap**", ""]
    for item in items:
        priority_marker = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(item.priority, "⚪")
        lines.append(f"  {priority_marker} {item.phase}: {item.title} [{item.priority}]")
    return "\n".join(lines)


# ── Report Integration ───────────────────────────────────────────────────────


def inject_visuals_into_markdown(md_content: str, results: dict) -> str:
    """Inject SVG charts and ASCII tables into Markdown report content."""
    profile = results.get("company_profile", {})
    seo = results.get("seo_keywords", {})
    competitor = results.get("competitor", {})
    swot = results.get("swot", {})
    score = results.get("prospect_score", {})

    lines = md_content.split("\n")
    new_lines: list[str] = []

    for line in lines:
        new_lines.append(line)

        # Inject SWOT quadrant after SWOT section header
        if line == "## 5. SWOT Analysis":
            model = build_swot_quadrant(swot)
            new_lines.append("")
            new_lines.append("```")
            new_lines.append(swot_quadrant_ascii(model))
            new_lines.append("```")
            new_lines.append("")

        # Inject competitor radar chart
        if line == "## 3. Competitor Landscape":
            model = build_radar_chart(competitor)
            if model.series:
                new_lines.append("")
                new_lines.append("```")
                new_lines.append(radar_chart_ascii(model))
                new_lines.append("```")
                new_lines.append("")

        # Inject content gap bar chart
        if line == "## 2. SEO & Keyword Analysis":
            model = build_content_gap_chart(seo)
            if model.items:
                new_lines.append("")
                new_lines.append("```")
                new_lines.append(bar_chart_ascii(model))
                new_lines.append("```")
                new_lines.append("")

        # Inject score donut
        if line == "## 9. Prospect Score":
            model = build_score_donut(score)
            new_lines.append("")
            new_lines.append("```")
            new_lines.append(score_donut_ascii(model))
            new_lines.append("```")
            new_lines.append("")

    # Add roadmap at end before evidence
    roadmap_items = build_automation_roadmap(swot)
    roadmap_text = roadmap_ascii(roadmap_items)
    evidence_marker = "## Evidence Sources"
    final_lines: list[str] = []
    for line in new_lines:
        if line == evidence_marker:
            final_lines.append("")
            final_lines.append("## Automation Roadmap")
            final_lines.append("")
            final_lines.append(roadmap_text)
            final_lines.append("")
            final_lines.append("---")
            final_lines.append("")
        final_lines.append(line)

    return "\n".join(final_lines)


def inject_visuals_into_html(html_content: str, results: dict) -> str:
    """Inject SVG charts into HTML report content (replaces ASCII placeholders)."""
    profile = results.get("company_profile", {})
    seo = results.get("seo_keywords", {})
    competitor = results.get("competitor", {})
    swot = results.get("swot", {})
    score = results.get("prospect_score", {})

    # SWOT SVG
    swot_model = build_swot_quadrant(swot)
    swot_svg = swot_quadrant_svg(swot_model)
    html_content = html_content.replace(
        "<code>┌──────────────────┬──────────────────┐",
        swot_svg
    )

    # Radar chart SVG
    radar_model = build_radar_chart(competitor)
    if radar_model.series:
        radar_svg = radar_chart_svg(radar_model)
        html_content = html_content.replace(
            "<code>Competitor",
            radar_svg
        )

    # Bar chart SVG
    bar_model = build_content_gap_chart(seo)
    if bar_model.items:
        bar_svg = bar_chart_svg(bar_model)
        html_content = html_content.replace(
            "<code>**Content Gaps",
            bar_svg
        )

    # Score donut SVG
    score_model = build_score_donut(score)
    if score_model.overall > 0:
        score_svg = score_donut_svg(score_model)
        html_content = html_content.replace(
            "<code>**Score:",
            score_svg
        )

    # Roadmap SVG
    roadmap_items = build_automation_roadmap(swot)
    roadmap_s = roadmap_svg(roadmap_items)
    html_content = html_content.replace(
        "<h2>Automation Roadmap</h2>",
        f"<h2>Automation Roadmap</h2>{roadmap_s}"
    )

    return html_content
